In [3]:
# Week 6
# 1.a - Enter each of the matrices A, B, and C as Numpy array. 
import numpy as np

# Matrix A
A = np.array([
    [1, -2, 3, 7],
    [2, 1, 1, 4],
    [-3, 2, -2, 10]
])

# Matrix B
B = np.array([
    [0, 1, -3, -2],
    [10, -1, 2, -3],
    [5, 1, -1, 4]
])

# Matrix C
C = np.array([
    [4, 0, -2, 3],
    [3, 6, 9, 7],
    [2, 2, 5, 1],
    [9, 4, 6, -2]
])

# check
print("Matrix A", A)
print("Matrix B", B) 
print("Matrix C", C)

Matrix A [[ 1 -2  3  7]
 [ 2  1  1  4]
 [-3  2 -2 10]]
Matrix B [[ 0  1 -3 -2]
 [10 -1  2 -3]
 [ 5  1 -1  4]]
Matrix C [[ 4  0 -2  3]
 [ 3  6  9  7]
 [ 2  2  5  1]
 [ 9  4  6 -2]]


In [5]:
# 1.b - What are the dimensions of each of the matrices A, B, and C? 
# Display these using Python code. 

print("Dimensions of Matrix A:", A.shape)
print("Dimensions of Matrix B:", B.shape)
print("Dimensions of Matrix C:", C.shape)

Dimensions of Matrix A: (3, 4)
Dimensions of Matrix B: (3, 4)
Dimensions of Matrix C: (4, 4)


In [12]:
# 3 - Determine if each of the following matrix operations is defined. If it is defined, calculate the result 
# using Python. If it is not defined, explain why it is not defined. 

# a) A+B
try:
    result = A + B
    print("A + B is defined:\n", result)
except ValueError as e:
    print("A + B is not defined:", e)
# b) AB
try:
    result_ab = A * B
    print("Result of AB:\n", result_ab)
except ValueError as e:
    print("AB is not defined:", e)
# c) AC
try:
    result_ac = A * C
    print("Result of AC:\n", result_ac)
except ValueError as e:
    print("AC is not defined:", e,
         "The shapes don't match")
# d) C^T (transpose)

CT = C.T
print("C Transposed:", CT)

A + B is defined:
 [[ 1 -1  0  5]
 [12  0  3  1]
 [ 2  3 -3 14]]
Result of AB:
 [[  0  -2  -9 -14]
 [ 20  -1   2 -12]
 [-15   2   2  40]]
AC is not defined: operands could not be broadcast together with shapes (3,4) (4,4)  The shapes don't match
C Transposed: [[ 4  3  2  9]
 [ 0  6  2  4]
 [-2  9  5  6]
 [ 3  7  1 -2]]


In [3]:
# 2.a - I could not for the life of me get cv2 to work on my computer, so 
# I used something else to load the image. I think my computer just hates OpenCV
from PIL import Image

# Load the image 
img = Image.open("C:/Users/vampr/Desktop/week7_image.jpg")

# Display the image
img.show()

In [7]:
# 2.b & 2.c
from PIL import Image
import numpy as np

# Load the image
img = Image.open("C:/Users/vampr/Desktop/week7_image.jpg")

# Convert to NumPy array
img_array = np.array(img)

# Get shape (height, width, color channels)
print("Image shape:", img_array.shape)

# resolution
height, width = img_array.shape[:2]
print("Resolution:", width, "x", height)
print("The 3rd number in the image shape is for the channels, or colors. There is not a thrid number if the image is black and white")

Image shape: (453, 600, 3)
Resolution: 600 x 453
The 3rd number in the image shape is for the channels, or colors. There is not a thrid number if the image is black and white
